version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    networks:
      - laravel
    expose:
      - 9000

  db:
    image: mysql:8
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: veterinario
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - laravel

  web:
    image: nginx:alpine
    volumes:
      - .:/var/www/html
      - .nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8000:80"
    depends_on:
      - app
    networks:
      - laravel

volumes:
  db_data:


networks:
  laravel:
    driver: bridge
