version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: veterinario_app
    container_name: veterinario_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    ports:
      - "9000:9000"
    env_file:
      - .env

