version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: veterinario_app
    container_name: veterinario_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    ports:
      - "8000:80"  # Cambiado de 9000:9000 a 8000:80
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: veterinario_db
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"

  jenkins:
    build:
      context: ./jenkins-docker
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  dbdata:
  jenkins_home:
